import React, { useEffect } from 'react';
import { withRouter } from 'react-router-dom';
import Account from './Account';
import AccessDeniedComp from './AccessDenied';
import ConfirmEmailComp from './ConfirmEmail';
import ConfirmEmailChangeComp from './ConfirmEmailChange';
import ExternalLoginComp from './ExternalLogin';
import ForgotPasswordComp from './ForgotPassword';
import ForgotPasswordConfirmationComp from './ForgotPasswordConfirmation';
import LockoutComp from './Lockout';
import LoginComp from './Login';
import LoginPartialComp from './LoginPartial';
import LoginWith2faComp from './LoginWith2fa';
import LoginWithRecoveryCodeComp from './LoginWithRecoveryCode';
import LogoutComp from './Logout';
import RegisterComp from './Register';
import RegisterConfirmationComp from './RegisterConfirmation';
import ResendEmailConfirmationComp from './ResendEmailConfirmation';
import ResetPasswordComp from './ResetPassword';
import ResetPasswordConfirmationComp from './ResetPasswordConfirmation';


export default Account;
export const AccessDenied = withRouter(AccessDeniedComp);
export const ConfirmEmail = withRouter(ConfirmEmailComp);
export const ConfirmEmailChange = withRouter(ConfirmEmailChangeComp);
export const ExternalLogin = withRouter(ExternalLoginComp);
export const ForgotPassword = withRouter(ForgotPasswordComp);
export const ForgotPasswordConfirmation = withRouter(ForgotPasswordConfirmationComp);
export const Lockout = withRouter(LockoutComp);
export const Login = withRouter(LoginComp);
export const LoginPartial = withRouter(LoginPartialComp);
export const LoginWith2fa = withRouter(LoginWith2faComp);
export const LoginWithRecoveryCode = withRouter(LoginWithRecoveryCodeComp);
export const Logout = withRouter(LogoutComp);
export const Register = withRouter(RegisterComp);
export const RegisterConfirmation = withRouter(RegisterConfirmationComp);
export const ResendEmailConfirmation = withRouter(ResendEmailConfirmationComp);
export const ResetPassword = withRouter(ResetPasswordComp);
export const ResetPasswordConfirmation = withRouter(ResetPasswordConfirmationComp);